name: AIMachina Library

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:

        runs-on: ubuntu-latest
        steps:

        - uses: actions/checkout@v2

        - name: Set up python
          uses: actions/setup-python@v2
          with:
              python-version: '3.8'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest pyyaml

        - name: Run unit tests
          run: |
              PYTHONPATH=`pwd` pytest -v tests/unit

        - name: Failure Notification
          if: ${{ failure() }}
          uses: rtCamp/action-slack-notify@v2.0.2
          env:
            SLACK_CHANNEL: aimachina_n_github
            SLACK_COLOR: '#ba382f'
            SLACK_ICON: https://66.media.tumblr.com/335adb3dfa9512a77cd67b95103cf9bc/tumblr_of45t8Q37N1voqnhpo3_250.png
            SLACK_MESSAGE: Some test for aimachina/library have failed
            SLACK_TITLE: TESTS FAILURE
            SLACK_USERNAME: github
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

        - name: Success Notification
          if: ${{ success() }}
          uses: rtCamp/action-slack-notify@v2.0.2
          env:
            SLACK_CHANNEL: aimachina_n_github
            SLACK_COLOR: '#2bb53c'
            SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/Octocat.png
            SLACK_MESSAGE: AIMachina Library passed all tests.
            SLACK_TITLE: ALL TESTS PASSED
            SLACK_USERNAME: github
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
