name: Publish Library packages
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [pypi-package]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: self-hosted

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Project checkout
              uses: actions/checkout@v2
            
            - name: Publish
              run: |
                  python3 -m venv venv
                  source venv/bin/activate
                  pip install -U pip
                  pip install wheel setuptools twine
                  python3.8 setup.py sdist bdist_wheel
                  twine upload --repository pypi dist/*

            - name: Clean
              if: ${{ always() }}
              run: |
                  rm -r venv
